spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/video_share?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.200.130
      port: 6379
      timeout: 6000
      password: 123
  mail:
    host: smtp.qq.com
    username: 1175414205@qq.com
    password: swuwzbhcjhryhchh
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  endpoint: http://192.168.200.130:9000
  accessKey: cle
  secretKey: 98735521
  bucket: video-share
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-va lue: 0 # 逻辑未删除值(默认为 0)